apiVersion: apps/v1
kind: Deployment
metadata:
  name: letskube-deployment
  labels:
    app: letskube
spec:
  replicas: 2
  template:
    metadata:
      name: letskube
      labels:
        app: letskube
    spec:
      containers:
      - name: letskube
        image: arturkarbone/letskube
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 80
          successThreshold: 3
          failureThreshold: 3
          periodSeconds: 10
          timeoutSeconds: 1
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 80
          failureThreshold: 7
          periodSeconds: 10
          timeoutSeconds: 1
          initialDelaySeconds: 0
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: letskube


---

apiVersion: v1
kind: Service
metadata:
  name: letskube-service
spec:
  selector:
    app: letskube
  ports:
    - port: 80
  type: NodePort
  
  